title: "Floral Facts"
encoding: UTF-8
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
collections:
  play:
    output: true
exclude:
  - node_modules/*
  - flower_imaegs/*
  - package-lock.json
  - package.json
  - make_puzzle_files.js
  - build.js